vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

    mappings:
        novels:
            uri_prefix: /images/novels
            upload_destination: '%kernel.project_dir%/public/images/novels'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true